timesteps 1000000
mpirun: killing job...

Failed to import the site module
Failed to import the site module
Failed to import the site module
Failed to import the site module
Failed to import the site module
Failed to import the site module
Failed to import the site module
Traceback (most recent call last):
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 567, in <module>
    main()
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 550, in main
    known_paths = addsitepackages(known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 327, in addsitepackages
    addsitedir(sitedir, known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 206, in addsitedir
    addpackage(sitedir, name, known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 167, in addpackage
    exec(line)
  File "<string>", line 1, in <module>
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/types.py", line 166, in <module>
    import functools as _functools
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 954, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 896, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1139, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1113, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1248, in find_spec
  File "<frozen importlib._bootstrap_external>", line 53, in _path_join
  File "<frozen importlib._bootstrap_external>", line 53, in <listcomp>
KeyboardInterrupt
Traceback (most recent call last):
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 567, in <module>
    main()
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 550, in main
    known_paths = addsitepackages(known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 327, in addsitepackages
    addsitedir(sitedir, known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 206, in addsitedir
    addpackage(sitedir, name, known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 167, in addpackage
    exec(line)
  File "<string>", line 1, in <module>
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/types.py", line 166, in <module>
    import functools as _functools
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 661, in exec_module
  File "<frozen importlib._bootstrap_external>", line 757, in get_code
  File "<frozen importlib._bootstrap_external>", line 455, in _validate_bytecode_header
KeyboardInterrupt
Traceback (most recent call last):
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 567, in <module>
    main()
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 550, in main
    known_paths = addsitepackages(known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 327, in addsitepackages
    addsitedir(sitedir, known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 206, in addsitedir
    addpackage(sitedir, name, known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 167, in addpackage
    exec(line)
  File "<string>", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 663, in _load_unlocked
KeyboardInterrupt
Traceback (most recent call last):
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 567, in <module>
    main()
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 550, in main
    known_paths = addsitepackages(known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 327, in addsitepackages
    addsitedir(sitedir, known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 206, in addsitedir
    addpackage(sitedir, name, known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 167, in addpackage
    exec(line)
  File "<string>", line 1, in <module>
KeyboardInterrupt
Traceback (most recent call last):
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 567, in <module>
    main()
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 550, in main
    known_paths = addsitepackages(known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 327, in addsitepackages
    addsitedir(sitedir, known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 204, in addsitedir
    names = [name for name in names if name.endswith(".pth")]
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 204, in <listcomp>
    names = [name for name in names if name.endswith(".pth")]
KeyboardInterrupt
Failed to import the site module
Traceback (most recent call last):
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 567, in <module>
    main()
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 549, in main
    known_paths = addusersitepackages(known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 284, in addusersitepackages
    addsitedir(user_site, known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 201, in addsitedir
    names = os.listdir(sitedir)
KeyboardInterrupt

real	0m0.085s
user	0m0.337s
sys	0m0.081s
mpirun: killing job...

Failed to import the site module
Failed to import the site module
Failed to import the site module
Failed to import the site module
Failed to import the site module
Failed to import the site module
Failed to import the site module
Traceback (most recent call last):
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 567, in <module>
    main()
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 550, in main
    known_paths = addsitepackages(known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 327, in addsitepackages
    addsitedir(sitedir, known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 206, in addsitedir
    addpackage(sitedir, name, known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 167, in addpackage
    exec(line)
  File "<string>", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 954, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 896, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1139, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1113, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1252, in find_spec
KeyboardInterrupt
Traceback (most recent call last):
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 567, in <module>
    main()
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 550, in main
    known_paths = addsitepackages(known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 327, in addsitepackages
    addsitedir(sitedir, known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 206, in addsitedir
    addpackage(sitedir, name, known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 167, in addpackage
    exec(line)
  File "<string>", line 1, in <module>
KeyboardInterrupt
Failed to import the site module
Traceback (most recent call last):
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 567, in <module>
    main()
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 550, in main
    known_paths = addsitepackages(known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 327, in addsitepackages
    addsitedir(sitedir, known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 206, in addsitedir
    addpackage(sitedir, name, known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 167, in addpackage
    exec(line)
  File "<string>", line 1, in <module>
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/types.py", line 166, in <module>
    import functools as _functools
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 954, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 896, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1139, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1113, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1251, in find_spec
  File "<frozen importlib._bootstrap_external>", line 89, in _path_isfile
  File "<frozen importlib._bootstrap_external>", line 81, in _path_is_mode_type
  File "<frozen importlib._bootstrap_external>", line 75, in _path_stat
KeyboardInterrupt
Traceback (most recent call last):
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 567, in <module>
    main()
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 550, in main
    known_paths = addsitepackages(known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 327, in addsitepackages
    addsitedir(sitedir, known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 206, in addsitedir
    addpackage(sitedir, name, known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 167, in addpackage
    exec(line)
  File "<string>", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 661, in exec_module
  File "<frozen importlib._bootstrap_external>", line 765, in get_code
  File "<frozen importlib._bootstrap_external>", line 480, in _compile_bytecode
KeyboardInterrupt

real	0m0.086s
user	0m0.338s
sys	0m0.083s
mpirun: killing job...

Failed to import the site module
Failed to import the site module
Failed to import the site module
Failed to import the site module
Failed to import the site module
Failed to import the site module
Traceback (most recent call last):
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 567, in <module>
    main()
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 549, in main
    known_paths = addusersitepackages(known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 281, in addusersitepackages
    user_site = getusersitepackages()
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 270, in getusersitepackages
    USER_SITE = get_path('purelib', '%s_user' % os.name)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/sysconfig.py", line 498, in get_path
    return get_paths(scheme, vars, expand)[name]
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/sysconfig.py", line 488, in get_paths
    return _expand_vars(scheme, vars)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/sysconfig.py", line 164, in _expand_vars
    _extend_dict(vars, get_config_vars())
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/sysconfig.py", line 155, in _extend_dict
    if key in target_keys:
KeyboardInterrupt
Traceback (most recent call last):
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 567, in <module>
    main()
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 549, in main
    known_paths = addusersitepackages(known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 281, in addusersitepackages
    user_site = getusersitepackages()
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 257, in getusersitepackages
    user_base = getuserbase() # this will also set USER_BASE
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 247, in getuserbase
    USER_BASE = get_config_var('userbase')
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/sysconfig.py", line 587, in get_config_var
    return get_config_vars().get(name)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/sysconfig.py", line 566, in get_config_vars
    import _osx_support
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/_osx_support.py", line 4, in <module>
    import re
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/re.py", line 123, in <module>
    import sre_compile
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/sre_compile.py", line 14, in <module>
    import sre_parse
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 661, in exec_module
  File "<frozen importlib._bootstrap_external>", line 757, in get_code
  File "<frozen importlib._bootstrap_external>", line 471, in _validate_bytecode_header
KeyboardInterrupt
Traceback (most recent call last):
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 567, in <module>
    main()
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 549, in main
    known_paths = addusersitepackages(known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 281, in addusersitepackages
    user_site = getusersitepackages()
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 257, in getusersitepackages
    user_base = getuserbase() # this will also set USER_BASE
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 247, in getuserbase
    USER_BASE = get_config_var('userbase')
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/sysconfig.py", line 587, in get_config_var
    return get_config_vars().get(name)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/sysconfig.py", line 566, in get_config_vars
    import _osx_support
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/_osx_support.py", line 4, in <module>
    import re
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 954, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 888, in _find_spec
  File "<frozen importlib._bootstrap>", line 854, in __enter__
KeyboardInterrupt
Failed to import the site module
Traceback (most recent call last):
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 567, in <module>
    main()
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 549, in main
    known_paths = addusersitepackages(known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 281, in addusersitepackages
    user_site = getusersitepackages()
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 257, in getusersitepackages
    user_base = getuserbase() # this will also set USER_BASE
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 247, in getuserbase
    USER_BASE = get_config_var('userbase')
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/sysconfig.py", line 587, in get_config_var
    return get_config_vars().get(name)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/sysconfig.py", line 536, in get_config_vars
    _init_posix(_CONFIG_VARS)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/sysconfig.py", line 408, in _init_posix
    from _sysconfigdata import build_time_vars
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 661, in exec_module
  File "<frozen importlib._bootstrap_external>", line 765, in get_code
  File "<frozen importlib._bootstrap_external>", line 476, in _compile_bytecode
KeyboardInterrupt

real	0m0.082s
user	0m0.284s
sys	0m0.075s
mpirun: killing job...

Failed to import the site module
Failed to import the site module
Failed to import the site module
Failed to import the site module
Failed to import the site module
Failed to import the site module
Failed to import the site module
Traceback (most recent call last):
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 567, in <module>
    main()
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 550, in main
    known_paths = addsitepackages(known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 327, in addsitepackages
    addsitedir(sitedir, known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 206, in addsitedir
    addpackage(sitedir, name, known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 167, in addpackage
    exec(line)
  File "<string>", line 1, in <module>
KeyboardInterrupt
Traceback (most recent call last):
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 567, in <module>
    main()
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 549, in main
    known_paths = addusersitepackages(known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 281, in addusersitepackages
    user_site = getusersitepackages()
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 257, in getusersitepackages
    user_base = getuserbase() # this will also set USER_BASE
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 247, in getuserbase
    USER_BASE = get_config_var('userbase')
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/sysconfig.py", line 587, in get_config_var
    return get_config_vars().get(name)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/sysconfig.py", line 567, in get_config_vars
    _osx_support.customize_config_vars(_CONFIG_VARS)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/_osx_support.py", line 393, in customize_config_vars
    if not _supports_universal_builds():
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/_osx_support.py", line 135, in _supports_universal_builds
    osx_version = _get_system_version()
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/_osx_support.py", line 96, in _get_system_version
    f = open('/System/Library/CoreServices/SystemVersion.plist')
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 954, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 896, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1139, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1110, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1064, in _path_importer_cache
KeyboardInterrupt
Traceback (most recent call last):
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 567, in <module>
    main()
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 549, in main
    known_paths = addusersitepackages(known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 281, in addusersitepackages
    user_site = getusersitepackages()
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 257, in getusersitepackages
    user_base = getuserbase() # this will also set USER_BASE
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 247, in getuserbase
    USER_BASE = get_config_var('userbase')
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/sysconfig.py", line 587, in get_config_var
    return get_config_vars().get(name)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/sysconfig.py", line 567, in get_config_vars
    _osx_support.customize_config_vars(_CONFIG_VARS)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/_osx_support.py", line 393, in customize_config_vars
    if not _supports_universal_builds():
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/_osx_support.py", line 135, in _supports_universal_builds
    osx_version = _get_system_version()
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/_osx_support.py", line 96, in _get_system_version
    f = open('/System/Library/CoreServices/SystemVersion.plist')
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 661, in exec_module
  File "<frozen importlib._bootstrap_external>", line 750, in get_code
  File "<frozen importlib._bootstrap_external>", line 819, in get_data
KeyboardInterrupt
Traceback (most recent call last):
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 567, in <module>
    main()
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 549, in main
    known_paths = addusersitepackages(known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 281, in addusersitepackages
    user_site = getusersitepackages()
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 257, in getusersitepackages
    user_base = getuserbase() # this will also set USER_BASE
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 247, in getuserbase
    USER_BASE = get_config_var('userbase')
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/sysconfig.py", line 587, in get_config_var
    return get_config_vars().get(name)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/sysconfig.py", line 566, in get_config_vars
    import _osx_support
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/_osx_support.py", line 4, in <module>
    import re
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/re.py", line 123, in <module>
    import sre_compile
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/sre_compile.py", line 14, in <module>
    import sre_parse
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/sre_parse.py", line 15, in <module>
    from sre_constants import *
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/sre_constants.py", line 102, in <module>
    """)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/sre_constants.py", line 58, in _makecodes
    items = [_NamedIntConstant(i, name) for i, name in enumerate(names)]
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/sre_constants.py", line 58, in <listcomp>
    items = [_NamedIntConstant(i, name) for i, name in enumerate(names)]
KeyboardInterrupt
Traceback (most recent call last):
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 567, in <module>
    main()
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 549, in main
    known_paths = addusersitepackages(known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 281, in addusersitepackages
    user_site = getusersitepackages()
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 257, in getusersitepackages
    user_base = getuserbase() # this will also set USER_BASE
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 247, in getuserbase
    USER_BASE = get_config_var('userbase')
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/sysconfig.py", line 587, in get_config_var
    return get_config_vars().get(name)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/sysconfig.py", line 566, in get_config_vars
    import _osx_support
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/_osx_support.py", line 4, in <module>
    import re
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/re.py", line 123, in <module>
    import sre_compile
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 954, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 896, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1139, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1113, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1221, in find_spec
  File "<frozen importlib._bootstrap_external>", line 75, in _path_stat
KeyboardInterrupt
Failed to import the site module

real	0m0.082s
user	0m0.309s
sys	0m0.080s
mpirun: killing job...

Failed to import the site module
Failed to import the site module
Failed to import the site module
Traceback (most recent call last):
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 567, in <module>
    main()
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 550, in main
    known_paths = addsitepackages(known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 327, in addsitepackages
    addsitedir(sitedir, known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 206, in addsitedir
    addpackage(sitedir, name, known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 167, in addpackage
    exec(line)
  File "<string>", line 1, in <module>
KeyboardInterrupt
Failed to import the site module
Traceback (most recent call last):
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 567, in <module>
    main()
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 550, in main
    known_paths = addsitepackages(known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 327, in addsitepackages
    addsitedir(sitedir, known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 206, in addsitedir
    addpackage(sitedir, name, known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 167, in addpackage
    exec(line)
  File "<string>", line 1, in <module>
KeyboardInterrupt
Failed to import the site module
Traceback (most recent call last):
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 567, in <module>
    main()
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 550, in main
    known_paths = addsitepackages(known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 327, in addsitepackages
    addsitedir(sitedir, known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 206, in addsitedir
    addpackage(sitedir, name, known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 162, in addpackage
    for n, line in enumerate(f):
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/codecs.py", line 318, in decode
    def decode(self, input, final=False):
KeyboardInterrupt
Failed to import the site module
Traceback (most recent call last):
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 567, in <module>
    main()
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 550, in main
    known_paths = addsitepackages(known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 327, in addsitepackages
    addsitedir(sitedir, known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 204, in addsitedir
    names = [name for name in names if name.endswith(".pth")]
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 204, in <listcomp>
    names = [name for name in names if name.endswith(".pth")]
KeyboardInterrupt
Failed to import the site module
Traceback (most recent call last):
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 567, in <module>
    main()
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 549, in main
    known_paths = addusersitepackages(known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 281, in addusersitepackages
    user_site = getusersitepackages()
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 257, in getusersitepackages
    user_base = getuserbase() # this will also set USER_BASE
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 247, in getuserbase
    USER_BASE = get_config_var('userbase')
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/sysconfig.py", line 587, in get_config_var
    return get_config_vars().get(name)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/sysconfig.py", line 567, in get_config_vars
    _osx_support.customize_config_vars(_CONFIG_VARS)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/_osx_support.py", line 404, in customize_config_vars
    _check_for_unavailable_sdk(_config_vars)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/_osx_support.py", line 290, in _check_for_unavailable_sdk
    m = re.search(r'-isysroot\s+(\S+)', cflags)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/re.py", line 173, in search
    return _compile(pattern, flags).search(string)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/re.py", line 293, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/sre_compile.py", line 536, in compile
    p = sre_parse.parse(p, flags)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/sre_parse.py", line 825, in parse
    pattern = Pattern()
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/sre_parse.py", line 73, in __init__
    self.groupwidths = [None]  # group 0
KeyboardInterrupt
Traceback (most recent call last):
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 567, in <module>
    main()
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 549, in main
    known_paths = addusersitepackages(known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 281, in addusersitepackages
    user_site = getusersitepackages()
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 257, in getusersitepackages
    user_base = getuserbase() # this will also set USER_BASE
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 247, in getuserbase
    USER_BASE = get_config_var('userbase')
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/sysconfig.py", line 587, in get_config_var
    return get_config_vars().get(name)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/sysconfig.py", line 567, in get_config_vars
    _osx_support.customize_config_vars(_CONFIG_VARS)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/_osx_support.py", line 393, in customize_config_vars
    if not _supports_universal_builds():
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/_osx_support.py", line 135, in _supports_universal_builds
    osx_version = _get_system_version()
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/_osx_support.py", line 96, in _get_system_version
    f = open('/System/Library/CoreServices/SystemVersion.plist')
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 661, in exec_module
  File "<frozen importlib._bootstrap_external>", line 750, in get_code
  File "<frozen importlib._bootstrap_external>", line 818, in get_data
KeyboardInterrupt
Failed to import the site module

real	0m0.081s
user	0m0.316s
sys	0m0.079s
timesteps 2000000
mpirun: killing job...

Failed to import the site module
Failed to import the site module
Failed to import the site module
Failed to import the site module
Failed to import the site module
Failed to import the site module
Traceback (most recent call last):
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 567, in <module>
    main()
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 550, in main
    known_paths = addsitepackages(known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 327, in addsitepackages
    addsitedir(sitedir, known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 206, in addsitedir
    addpackage(sitedir, name, known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 167, in addpackage
    exec(line)
  File "<string>", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 661, in exec_module
  File "<frozen importlib._bootstrap_external>", line 765, in get_code
  File "<frozen importlib._bootstrap_external>", line 476, in _compile_bytecode
KeyboardInterrupt
Failed to import the site module
Traceback (most recent call last):
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 567, in <module>
    main()
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 550, in main
    known_paths = addsitepackages(known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 327, in addsitepackages
    addsitedir(sitedir, known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 206, in addsitedir
    addpackage(sitedir, name, known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 167, in addpackage
    exec(line)
  File "<string>", line 1, in <module>
KeyboardInterrupt
Failed to import the site module
Traceback (most recent call last):
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 567, in <module>
    main()
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 550, in main
    known_paths = addsitepackages(known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 327, in addsitepackages
    addsitedir(sitedir, known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 206, in addsitedir
    addpackage(sitedir, name, known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 162, in addpackage
    for n, line in enumerate(f):
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/codecs.py", line 318, in decode
    def decode(self, input, final=False):
KeyboardInterrupt
Traceback (most recent call last):
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 567, in <module>
    main()
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 549, in main
    known_paths = addusersitepackages(known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 281, in addusersitepackages
    user_site = getusersitepackages()
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 257, in getusersitepackages
    user_base = getuserbase() # this will also set USER_BASE
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 247, in getuserbase
    USER_BASE = get_config_var('userbase')
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/sysconfig.py", line 587, in get_config_var
    return get_config_vars().get(name)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/sysconfig.py", line 567, in get_config_vars
    _osx_support.customize_config_vars(_CONFIG_VARS)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/_osx_support.py", line 393, in customize_config_vars
    if not _supports_universal_builds():
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/_osx_support.py", line 135, in _supports_universal_builds
    osx_version = _get_system_version()
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/_osx_support.py", line 104, in _get_system_version
    r'<string>(.*?)</string>', f.read())
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/re.py", line 173, in search
    return _compile(pattern, flags).search(string)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/re.py", line 293, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/sre_compile.py", line 536, in compile
    p = sre_parse.parse(p, flags)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/sre_parse.py", line 829, in parse
    p = _parse_sub(source, pattern, 0)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/sre_parse.py", line 437, in _parse_sub
    itemsappend(_parse(source, state))
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/sre_parse.py", line 523, in _parse
    if this[0] == "\\":
KeyboardInterrupt

real	0m0.085s
user	0m0.330s
sys	0m0.082s
mpirun: killing job...

Failed to import the site module
Failed to import the site module
Failed to import the site module
Failed to import the site module
Failed to import the site module
Failed to import the site module
Failed to import the site module
Failed to import the site module
Traceback (most recent call last):
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 567, in <module>
    main()
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 550, in main
    known_paths = addsitepackages(known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 327, in addsitepackages
    addsitedir(sitedir, known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 206, in addsitedir
    addpackage(sitedir, name, known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 162, in addpackage
    for n, line in enumerate(f):
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/codecs.py", line 318, in decode
    def decode(self, input, final=False):
KeyboardInterrupt
Traceback (most recent call last):
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 567, in <module>
    main()
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 550, in main
    known_paths = addsitepackages(known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 327, in addsitepackages
    addsitedir(sitedir, known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 206, in addsitedir
    addpackage(sitedir, name, known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 167, in addpackage
    exec(line)
  File "<string>", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 954, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 888, in _find_spec
  File "<frozen importlib._bootstrap>", line 854, in __enter__
KeyboardInterrupt
Traceback (most recent call last):
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 567, in <module>
    main()
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 549, in main
    known_paths = addusersitepackages(known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 281, in addusersitepackages
    user_site = getusersitepackages()
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 257, in getusersitepackages
    user_base = getuserbase() # this will also set USER_BASE
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 247, in getuserbase
    USER_BASE = get_config_var('userbase')
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/sysconfig.py", line 587, in get_config_var
    return get_config_vars().get(name)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/sysconfig.py", line 567, in get_config_vars
    _osx_support.customize_config_vars(_CONFIG_VARS)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/_osx_support.py", line 393, in customize_config_vars
    if not _supports_universal_builds():
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/_osx_support.py", line 135, in _supports_universal_builds
    osx_version = _get_system_version()
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/_osx_support.py", line 96, in _get_system_version
    f = open('/System/Library/CoreServices/SystemVersion.plist')
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 954, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 896, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1139, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1113, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1221, in find_spec
KeyboardInterrupt
Traceback (most recent call last):
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 567, in <module>
    main()
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 549, in main
    known_paths = addusersitepackages(known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 281, in addusersitepackages
    user_site = getusersitepackages()
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 257, in getusersitepackages
    user_base = getuserbase() # this will also set USER_BASE
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 247, in getuserbase
    USER_BASE = get_config_var('userbase')
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/sysconfig.py", line 587, in get_config_var
    return get_config_vars().get(name)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/sysconfig.py", line 567, in get_config_vars
    _osx_support.customize_config_vars(_CONFIG_VARS)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/_osx_support.py", line 393, in customize_config_vars
    if not _supports_universal_builds():
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/_osx_support.py", line 135, in _supports_universal_builds
    osx_version = _get_system_version()
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/_osx_support.py", line 96, in _get_system_version
    f = open('/System/Library/CoreServices/SystemVersion.plist')
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 661, in exec_module
  File "<frozen importlib._bootstrap_external>", line 744, in get_code
  File "<frozen importlib._bootstrap_external>", line 828, in path_stats
  File "<frozen importlib._bootstrap_external>", line 75, in _path_stat
KeyboardInterrupt

real	0m0.085s
user	0m0.331s
sys	0m0.084s
mpirun: killing job...

Failed to import the site module
Failed to import the site module
Failed to import the site module
Failed to import the site module
Failed to import the site module
Failed to import the site module
Traceback (most recent call last):
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 567, in <module>
    main()
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 550, in main
    known_paths = addsitepackages(known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 327, in addsitepackages
    addsitedir(sitedir, known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 206, in addsitedir
    addpackage(sitedir, name, known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 162, in addpackage
    for n, line in enumerate(f):
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/codecs.py", line 318, in decode
    def decode(self, input, final=False):
KeyboardInterrupt
Traceback (most recent call last):
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 567, in <module>
    main()
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 550, in main
    known_paths = addsitepackages(known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 327, in addsitepackages
    addsitedir(sitedir, known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 206, in addsitedir
    addpackage(sitedir, name, known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 167, in addpackage
    exec(line)
  File "<string>", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 954, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 896, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1139, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1112, in _get_spec
KeyboardInterrupt
Failed to import the site module
Traceback (most recent call last):
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 567, in <module>
    main()
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 550, in main
    known_paths = addsitepackages(known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 327, in addsitepackages
    addsitedir(sitedir, known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 206, in addsitedir
    addpackage(sitedir, name, known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 162, in addpackage
    for n, line in enumerate(f):
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/codecs.py", line 318, in decode
    def decode(self, input, final=False):
KeyboardInterrupt
Traceback (most recent call last):
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 567, in <module>
    main()
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 550, in main
    known_paths = addsitepackages(known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 327, in addsitepackages
    addsitedir(sitedir, known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 206, in addsitedir
    addpackage(sitedir, name, known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 162, in addpackage
    for n, line in enumerate(f):
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/codecs.py", line 318, in decode
    def decode(self, input, final=False):
KeyboardInterrupt
Traceback (most recent call last):
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 567, in <module>
    main()
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 549, in main
    known_paths = addusersitepackages(known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 281, in addusersitepackages
    user_site = getusersitepackages()
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 257, in getusersitepackages
    user_base = getuserbase() # this will also set USER_BASE
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 247, in getuserbase
    USER_BASE = get_config_var('userbase')
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/sysconfig.py", line 587, in get_config_var
    return get_config_vars().get(name)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/sysconfig.py", line 566, in get_config_vars
    import _osx_support
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/_osx_support.py", line 4, in <module>
    import re
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 954, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 896, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1139, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1110, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1080, in _path_importer_cache
KeyboardInterrupt

real	0m0.085s
user	0m0.320s
sys	0m0.082s
mpirun: killing job...

Failed to import the site module
Failed to import the site module
Failed to import the site module
Failed to import the site module
Failed to import the site module
Traceback (most recent call last):
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 567, in <module>
    main()
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 550, in main
    known_paths = addsitepackages(known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 327, in addsitepackages
    addsitedir(sitedir, known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 206, in addsitedir
    addpackage(sitedir, name, known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 167, in addpackage
    exec(line)
  File "<string>", line 1, in <module>
KeyboardInterrupt
Failed to import the site module
Failed to import the site module
Traceback (most recent call last):
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 567, in <module>
    main()
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 550, in main
    known_paths = addsitepackages(known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 327, in addsitepackages
    addsitedir(sitedir, known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 205, in addsitedir
    for name in sorted(names):
KeyboardInterrupt
Failed to import the site module
Traceback (most recent call last):
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 567, in <module>
    main()
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 549, in main
    known_paths = addusersitepackages(known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 281, in addusersitepackages
    user_site = getusersitepackages()
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 257, in getusersitepackages
    user_base = getuserbase() # this will also set USER_BASE
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 247, in getuserbase
    USER_BASE = get_config_var('userbase')
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/sysconfig.py", line 587, in get_config_var
    return get_config_vars().get(name)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/sysconfig.py", line 567, in get_config_vars
    _osx_support.customize_config_vars(_CONFIG_VARS)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/_osx_support.py", line 393, in customize_config_vars
    if not _supports_universal_builds():
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/_osx_support.py", line 138, in _supports_universal_builds
    osx_version = tuple(int(i) for i in osx_version.split('.'))
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/_osx_support.py", line 138, in <genexpr>
    osx_version = tuple(int(i) for i in osx_version.split('.'))
KeyboardInterrupt
Traceback (most recent call last):
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 567, in <module>
    main()
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 550, in main
    known_paths = addsitepackages(known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 327, in addsitepackages
    addsitedir(sitedir, known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 206, in addsitedir
    addpackage(sitedir, name, known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 167, in addpackage
    exec(line)
  File "<string>", line 1, in <module>
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/types.py", line 166, in <module>
    import functools as _functools
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/functools.py", line 21, in <module>
    from collections import namedtuple
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/collections/__init__.py", line 26, in <module>
    from operator import itemgetter as _itemgetter, eq as _eq
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 666, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 582, in module_from_spec
KeyboardInterrupt
Traceback (most recent call last):
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 567, in <module>
    main()
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 549, in main
    known_paths = addusersitepackages(known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 281, in addusersitepackages
    user_site = getusersitepackages()
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 257, in getusersitepackages
    user_base = getuserbase() # this will also set USER_BASE
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 247, in getuserbase
    USER_BASE = get_config_var('userbase')
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/sysconfig.py", line 587, in get_config_var
    return get_config_vars().get(name)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/sysconfig.py", line 566, in get_config_vars
    import _osx_support
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/_osx_support.py", line 4, in <module>
    import re
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/re.py", line 345, in <module>
    class Scanner:
KeyboardInterrupt

real	0m0.087s
user	0m0.331s
sys	0m0.082s
mpirun: killing job...

Failed to import the site module
Failed to import the site module
Failed to import the site module
Failed to import the site module
Failed to import the site module
Failed to import the site module
Failed to import the site module
Traceback (most recent call last):
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 567, in <module>
    main()
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 550, in main
    known_paths = addsitepackages(known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 327, in addsitepackages
    addsitedir(sitedir, known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 206, in addsitedir
    addpackage(sitedir, name, known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 167, in addpackage
    exec(line)
  File "<string>", line 1, in <module>
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/types.py", line 166, in <module>
    import functools as _functools
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/functools.py", line 21, in <module>
    from collections import namedtuple
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/collections/__init__.py", line 26, in <module>
    from operator import itemgetter as _itemgetter, eq as _eq
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 661, in exec_module
  File "<frozen importlib._bootstrap_external>", line 750, in get_code
  File "<frozen importlib._bootstrap_external>", line 819, in get_data
KeyboardInterrupt
Traceback (most recent call last):
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 567, in <module>
    main()
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 550, in main
    known_paths = addsitepackages(known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 327, in addsitepackages
    addsitedir(sitedir, known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 206, in addsitedir
    addpackage(sitedir, name, known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 167, in addpackage
    exec(line)
  File "<string>", line 1, in <module>
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/types.py", line 166, in <module>
    import functools as _functools
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/functools.py", line 21, in <module>
    from collections import namedtuple
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/collections/__init__.py", line 27, in <module>
    from keyword import iskeyword as _iskeyword
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 661, in exec_module
  File "<frozen importlib._bootstrap_external>", line 750, in get_code
  File "<frozen importlib._bootstrap_external>", line 819, in get_data
KeyboardInterrupt
Failed to import the site module
Traceback (most recent call last):
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 567, in <module>
    main()
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 550, in main
    known_paths = addsitepackages(known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 327, in addsitepackages
    addsitedir(sitedir, known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 206, in addsitedir
    addpackage(sitedir, name, known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 167, in addpackage
    exec(line)
  File "<string>", line 1, in <module>
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/types.py", line 166, in <module>
    import functools as _functools
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 661, in exec_module
  File "<frozen importlib._bootstrap_external>", line 765, in get_code
  File "<frozen importlib._bootstrap_external>", line 476, in _compile_bytecode
KeyboardInterrupt
Traceback (most recent call last):
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 567, in <module>
    main()
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 550, in main
    known_paths = addsitepackages(known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 327, in addsitepackages
    addsitedir(sitedir, known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 206, in addsitedir
    addpackage(sitedir, name, known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 167, in addpackage
    exec(line)
  File "<string>", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 954, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 896, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1139, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1113, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1221, in find_spec
  File "<frozen importlib._bootstrap_external>", line 75, in _path_stat
KeyboardInterrupt

real	0m0.086s
user	0m0.347s
sys	0m0.084s
timesteps 3000000
mpirun: killing job...

Failed to import the site module
Failed to import the site module
Failed to import the site module
Failed to import the site module
Failed to import the site module
Traceback (most recent call last):
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 567, in <module>
    main()
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 550, in main
    known_paths = addsitepackages(known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 327, in addsitepackages
    addsitedir(sitedir, known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 206, in addsitedir
    addpackage(sitedir, name, known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 162, in addpackage
    for n, line in enumerate(f):
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/codecs.py", line 318, in decode
    def decode(self, input, final=False):
KeyboardInterrupt
Traceback (most recent call last):
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 567, in <module>
    main()
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 550, in main
    known_paths = addsitepackages(known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 327, in addsitepackages
    addsitedir(sitedir, known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 206, in addsitedir
    addpackage(sitedir, name, known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 167, in addpackage
    exec(line)
  File "<string>", line 1, in <module>
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/types.py", line 166, in <module>
    import functools as _functools
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/functools.py", line 21, in <module>
    from collections import namedtuple
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/collections/__init__.py", line 26, in <module>
    from operator import itemgetter as _itemgetter, eq as _eq
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 661, in exec_module
  File "<frozen importlib._bootstrap_external>", line 750, in get_code
  File "<frozen importlib._bootstrap_external>", line 818, in get_data
KeyboardInterrupt
Failed to import the site module
Traceback (most recent call last):
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 567, in <module>
    main()
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 550, in main
    known_paths = addsitepackages(known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 327, in addsitepackages
    addsitedir(sitedir, known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 206, in addsitedir
    addpackage(sitedir, name, known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 162, in addpackage
    for n, line in enumerate(f):
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/codecs.py", line 318, in decode
    def decode(self, input, final=False):
KeyboardInterrupt
Failed to import the site module
Traceback (most recent call last):
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 567, in <module>
    main()
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 549, in main
    known_paths = addusersitepackages(known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 284, in addusersitepackages
    addsitedir(user_site, known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 196, in addsitedir
    sitedir, sitedircase = makepath(sitedir)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 95, in makepath
    return dir, os.path.normcase(dir)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/posixpath.py", line 52, in normcase
    if not isinstance(s, (bytes, str)):
KeyboardInterrupt
Traceback (most recent call last):
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 567, in <module>
    main()
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 549, in main
    known_paths = addusersitepackages(known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 281, in addusersitepackages
    user_site = getusersitepackages()
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 257, in getusersitepackages
    user_base = getuserbase() # this will also set USER_BASE
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 247, in getuserbase
    USER_BASE = get_config_var('userbase')
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/sysconfig.py", line 587, in get_config_var
    return get_config_vars().get(name)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/sysconfig.py", line 566, in get_config_vars
    import _osx_support
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/_osx_support.py", line 4, in <module>
    import re
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/re.py", line 126, in <module>
    import _locale
KeyboardInterrupt
Failed to import the site module
Traceback (most recent call last):
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 567, in <module>
    main()
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 550, in main
    known_paths = addsitepackages(known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 325, in addsitepackages
    for sitedir in getsitepackages(prefixes):
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 315, in getsitepackages
    from sysconfig import get_config_var
  File "<frozen importlib._bootstrap>", line 996, in _handle_fromlist
KeyboardInterrupt

real	0m0.082s
user	0m0.316s
sys	0m0.080s
mpirun: killing job...

Failed to import the site module
Failed to import the site module
Failed to import the site module
Failed to import the site module
Failed to import the site module
Traceback (most recent call last):
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 567, in <module>
    main()
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 550, in main
    known_paths = addsitepackages(known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 327, in addsitepackages
    addsitedir(sitedir, known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 206, in addsitedir
    addpackage(sitedir, name, known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 167, in addpackage
    exec(line)
  File "<string>", line 1, in <module>
KeyboardInterrupt
Failed to import the site module
Traceback (most recent call last):
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 567, in <module>
    main()
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 550, in main
    known_paths = addsitepackages(known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 327, in addsitepackages
    addsitedir(sitedir, known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 206, in addsitedir
    addpackage(sitedir, name, known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 167, in addpackage
    exec(line)
  File "<string>", line 1, in <module>
KeyboardInterrupt
Failed to import the site module
Traceback (most recent call last):
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 567, in <module>
    main()
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 549, in main
    known_paths = addusersitepackages(known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 281, in addusersitepackages
    user_site = getusersitepackages()
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 257, in getusersitepackages
    user_base = getuserbase() # this will also set USER_BASE
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 247, in getuserbase
    USER_BASE = get_config_var('userbase')
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/sysconfig.py", line 587, in get_config_var
    return get_config_vars().get(name)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/sysconfig.py", line 566, in get_config_vars
    import _osx_support
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/_osx_support.py", line 4, in <module>
    import re
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/re.py", line 123, in <module>
    import sre_compile
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/sre_compile.py", line 14, in <module>
    import sre_parse
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 954, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 896, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1139, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1113, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1251, in find_spec
  File "<frozen importlib._bootstrap_external>", line 89, in _path_isfile
  File "<frozen importlib._bootstrap_external>", line 81, in _path_is_mode_type
  File "<frozen importlib._bootstrap_external>", line 75, in _path_stat
KeyboardInterrupt
Traceback (most recent call last):
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 567, in <module>
    main()
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 549, in main
    known_paths = addusersitepackages(known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 281, in addusersitepackages
    user_site = getusersitepackages()
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 257, in getusersitepackages
    user_base = getuserbase() # this will also set USER_BASE
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 247, in getuserbase
    USER_BASE = get_config_var('userbase')
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/sysconfig.py", line 587, in get_config_var
    return get_config_vars().get(name)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/sysconfig.py", line 566, in get_config_vars
    import _osx_support
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/_osx_support.py", line 4, in <module>
    import re
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/re.py", line 123, in <module>
    import sre_compile
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/sre_compile.py", line 14, in <module>
    import sre_parse
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/sre_parse.py", line 26, in <module>
    WHITESPACE = frozenset(" \t\n\r\v\f")
KeyboardInterrupt

real	0m0.083s
user	0m0.305s
sys	0m0.078s
mpirun: killing job...

Failed to import the site module
Failed to import the site module
Failed to import the site module
Failed to import the site module
Failed to import the site module
Failed to import the site module
Traceback (most recent call last):
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 567, in <module>
    main()
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 550, in main
    known_paths = addsitepackages(known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 327, in addsitepackages
    addsitedir(sitedir, known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 206, in addsitedir
    addpackage(sitedir, name, known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 162, in addpackage
    for n, line in enumerate(f):
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/codecs.py", line 318, in decode
    def decode(self, input, final=False):
KeyboardInterrupt
Traceback (most recent call last):
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 567, in <module>
    main()
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 549, in main
    known_paths = addusersitepackages(known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 281, in addusersitepackages
    user_site = getusersitepackages()
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 257, in getusersitepackages
    user_base = getuserbase() # this will also set USER_BASE
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 247, in getuserbase
    USER_BASE = get_config_var('userbase')
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/sysconfig.py", line 587, in get_config_var
    return get_config_vars().get(name)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/sysconfig.py", line 567, in get_config_vars
    _osx_support.customize_config_vars(_CONFIG_VARS)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/_osx_support.py", line 393, in customize_config_vars
    if not _supports_universal_builds():
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/_osx_support.py", line 135, in _supports_universal_builds
    osx_version = _get_system_version()
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/_osx_support.py", line 96, in _get_system_version
    f = open('/System/Library/CoreServices/SystemVersion.plist')
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 661, in exec_module
KeyboardInterrupt
Traceback (most recent call last):
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 567, in <module>
    main()
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 549, in main
    known_paths = addusersitepackages(known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 281, in addusersitepackages
    user_site = getusersitepackages()
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 257, in getusersitepackages
    user_base = getuserbase() # this will also set USER_BASE
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 247, in getuserbase
    USER_BASE = get_config_var('userbase')
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/sysconfig.py", line 587, in get_config_var
    return get_config_vars().get(name)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/sysconfig.py", line 566, in get_config_vars
    import _osx_support
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/_osx_support.py", line 11, in <module>
    'get_platform_osx',
KeyboardInterrupt
Failed to import the site module
Traceback (most recent call last):
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 567, in <module>
    main()
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 549, in main
    known_paths = addusersitepackages(known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 284, in addusersitepackages
    addsitedir(user_site, known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 206, in addsitedir
    addpackage(sitedir, name, known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 158, in addpackage
    f = open(fullname, "r")
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/_bootlocale.py", line 23, in getpreferredencoding
    def getpreferredencoding(do_setlocale=True):
KeyboardInterrupt
Failed to import the site module
Traceback (most recent call last):
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 567, in <module>
    main()
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 549, in main
    known_paths = addusersitepackages(known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 281, in addusersitepackages
    user_site = getusersitepackages()
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 257, in getusersitepackages
    user_base = getuserbase() # this will also set USER_BASE
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 247, in getuserbase
    USER_BASE = get_config_var('userbase')
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/sysconfig.py", line 587, in get_config_var
    return get_config_vars().get(name)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/sysconfig.py", line 567, in get_config_vars
    _osx_support.customize_config_vars(_CONFIG_VARS)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/_osx_support.py", line 393, in customize_config_vars
    if not _supports_universal_builds():
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/_osx_support.py", line 135, in _supports_universal_builds
    osx_version = _get_system_version()
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/_osx_support.py", line 104, in _get_system_version
    r'<string>(.*?)</string>', f.read())
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/re.py", line 173, in search
    return _compile(pattern, flags).search(string)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/re.py", line 293, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/sre_compile.py", line 540, in compile
    code = _code(p, flags)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/sre_compile.py", line 522, in _code
    _compile_info(code, p, flags)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/sre_compile.py", line 416, in _compile_info
    lo, hi = pattern.getwidth()
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/sre_parse.py", line 173, in getwidth
    if op is BRANCH:
KeyboardInterrupt

real	0m0.084s
user	0m0.323s
sys	0m0.080s
mpirun: killing job...

Failed to import the site module
Failed to import the site module
Traceback (most recent call last):
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 567, in <module>
    main()
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 550, in main
    known_paths = addsitepackages(known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 327, in addsitepackages
    addsitedir(sitedir, known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 206, in addsitedir
    addpackage(sitedir, name, known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 162, in addpackage
    for n, line in enumerate(f):
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/codecs.py", line 318, in decode
    def decode(self, input, final=False):
KeyboardInterrupt
Failed to import the site module
Failed to import the site module
Traceback (most recent call last):
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 567, in <module>
    main()
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 549, in main
    known_paths = addusersitepackages(known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 284, in addusersitepackages
    addsitedir(user_site, known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 206, in addsitedir
    addpackage(sitedir, name, known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 162, in addpackage
    for n, line in enumerate(f):
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/codecs.py", line 318, in decode
    def decode(self, input, final=False):
KeyboardInterrupt
Failed to import the site module
Traceback (most recent call last):
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 567, in <module>
    main()
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 549, in main
    known_paths = addusersitepackages(known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 281, in addusersitepackages
    user_site = getusersitepackages()
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 257, in getusersitepackages
    user_base = getuserbase() # this will also set USER_BASE
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 247, in getuserbase
    USER_BASE = get_config_var('userbase')
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/sysconfig.py", line 587, in get_config_var
    return get_config_vars().get(name)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/sysconfig.py", line 567, in get_config_vars
    _osx_support.customize_config_vars(_CONFIG_VARS)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/_osx_support.py", line 393, in customize_config_vars
    if not _supports_universal_builds():
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/_osx_support.py", line 135, in _supports_universal_builds
    osx_version = _get_system_version()
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/_osx_support.py", line 106, in _get_system_version
    f.close()
KeyboardInterrupt
Failed to import the site module
Traceback (most recent call last):
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 567, in <module>
    main()
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 549, in main
    known_paths = addusersitepackages(known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 281, in addusersitepackages
    user_site = getusersitepackages()
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 257, in getusersitepackages
    user_base = getuserbase() # this will also set USER_BASE
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 247, in getuserbase
    USER_BASE = get_config_var('userbase')
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/sysconfig.py", line 587, in get_config_var
    return get_config_vars().get(name)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/sysconfig.py", line 566, in get_config_vars
    import _osx_support
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/_osx_support.py", line 4, in <module>
    import re
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/re.py", line 123, in <module>
    import sre_compile
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/sre_compile.py", line 14, in <module>
    import sre_parse
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/sre_parse.py", line 15, in <module>
    from sre_constants import *
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 661, in exec_module
KeyboardInterrupt
Failed to import the site module
Traceback (most recent call last):
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 567, in <module>
    main()
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 549, in main
    known_paths = addusersitepackages(known_paths)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 281, in addusersitepackages
    user_site = getusersitepackages()
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 257, in getusersitepackages
    user_base = getuserbase() # this will also set USER_BASE
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 247, in getuserbase
    USER_BASE = get_config_var('userbase')
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/sysconfig.py", line 587, in get_config_var
    return get_config_vars().get(name)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/sysconfig.py", line 566, in get_config_vars
    import _osx_support
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/_osx_support.py", line 4, in <module>
    import re
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/re.py", line 123, in <module>
    import sre_compile
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/sre_compile.py", line 14, in <module>
    import sre_parse
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/sre_parse.py", line 68, in <module>
    class Pattern:
KeyboardInterrupt

real	0m0.082s
user	0m0.305s
sys	0m0.078s
mpirun: killing job...

Traceback (most recent call last):
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/codeMan/Desktop/mTRPO/mytrpo/trpo_mpi/run_mujoco.py", line 2, in <module>
    import tensorflow as tf
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site-packages/tensorflow/python/__init__.py", line 93, in <module>
    from tensorflow.python.ops.standard_ops import *
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site-packages/tensorflow/python/ops/standard_ops.py", line 28, in <module>
    from tensorflow.python.ops import math_grad
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site-packages/tensorflow/python/ops/math_grad.py", line 851, in <module>
    @ops.RegisterGradient("Rint")
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1634, in __call__
    _gradient_registry.register(f, self._op_type)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site-packages/tensorflow/python/framework/registry.py", line 67, in register
    stack = traceback.extract_stack()
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/traceback.py", line 207, in extract_stack
    stack = StackSummary.extract(walk_stack(f), limit=limit)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/traceback.py", line 358, in extract
    f.line
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/traceback.py", line 282, in line
    self._line = linecache.getline(self.filename, self.lineno).strip()
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/linecache.py", line 16, in getline
    lines = getlines(filename, module_globals)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/linecache.py", line 43, in getlines
    if len(entry) != 1:
KeyboardInterrupt
Traceback (most recent call last):
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/codeMan/Desktop/mTRPO/mytrpo/trpo_mpi/run_mujoco.py", line 2, in <module>
    import tensorflow as tf
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site-packages/tensorflow/python/__init__.py", line 93, in <module>
    from tensorflow.python.ops.standard_ops import *
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site-packages/tensorflow/python/ops/standard_ops.py", line 30, in <module>
    from tensorflow.python.ops import state_grad
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site-packages/tensorflow/python/ops/state_grad.py", line 39, in <module>
    ops.NotDifferentiable("ScatterSub")
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1668, in NotDifferentiable
    _gradient_registry.register(None, op_type)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site-packages/tensorflow/python/framework/registry.py", line 67, in register
    stack = traceback.extract_stack()
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/traceback.py", line 207, in extract_stack
    stack = StackSummary.extract(walk_stack(f), limit=limit)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/traceback.py", line 352, in extract
    filename, lineno, name, lookup_line=False, locals=f_locals))
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/traceback.py", line 250, in __init__
    self.filename = filename
KeyboardInterrupt
Traceback (most recent call last):
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/codeMan/Desktop/mTRPO/mytrpo/trpo_mpi/run_mujoco.py", line 2, in <module>
    import tensorflow as tf
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site-packages/tensorflow/python/__init__.py", line 93, in <module>
    from tensorflow.python.ops.standard_ops import *
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site-packages/tensorflow/python/ops/standard_ops.py", line 39, in <module>
    from tensorflow.python.ops.clip_ops import *
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site-packages/tensorflow/python/ops/clip_ops.py", line 29, in <module>
    from tensorflow.python.ops import gen_nn_ops
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 5902, in <module>
    _op_def_lib = _InitOpDefLibrary()
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 2468, in _InitOpDefLibrary
    _text_format.Merge(_InitOpDefLibrary.op_list_ascii, op_list)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site-packages/google/protobuf/text_format.py", line 525, in Merge
    descriptor_pool=descriptor_pool)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site-packages/google/protobuf/text_format.py", line 579, in MergeLines
    return parser.MergeLines(lines, message)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site-packages/google/protobuf/text_format.py", line 612, in MergeLines
    self._ParseOrMerge(lines, message)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site-packages/google/protobuf/text_format.py", line 627, in _ParseOrMerge
    self._MergeField(tokenizer, message)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site-packages/google/protobuf/text_format.py", line 727, in _MergeField
    merger(tokenizer, message, field)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site-packages/google/protobuf/text_format.py", line 815, in _MergeMessageField
    self._MergeField(tokenizer, sub_message)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site-packages/google/protobuf/text_format.py", line 727, in _MergeField
    merger(tokenizer, message, field)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site-packages/google/protobuf/text_format.py", line 815, in _MergeMessageField
    self._MergeField(tokenizer, sub_message)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site-packages/google/protobuf/text_format.py", line 727, in _MergeField
    merger(tokenizer, message, field)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site-packages/google/protobuf/text_format.py", line 769, in _MergeMessageField
    tokenizer.Consume('{')
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site-packages/google/protobuf/text_format.py", line 1078, in Consume
    if not self.TryConsume(token):
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site-packages/google/protobuf/text_format.py", line 1065, in TryConsume
    self.NextToken()
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site-packages/google/protobuf/text_format.py", line 1307, in NextToken
    self._column += len(self.token)
KeyboardInterrupt
Traceback (most recent call last):
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/codeMan/Desktop/mTRPO/mytrpo/trpo_mpi/run_mujoco.py", line 2, in <module>
    import tensorflow as tf
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site-packages/tensorflow/python/__init__.py", line 93, in <module>
    from tensorflow.python.ops.standard_ops import *
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site-packages/tensorflow/python/ops/standard_ops.py", line 29, in <module>
    from tensorflow.python.ops import sparse_grad
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site-packages/tensorflow/python/ops/sparse_grad.py", line 65, in <module>
    @ops.RegisterGradient("SparseAdd")
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1634, in __call__
    _gradient_registry.register(f, self._op_type)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site-packages/tensorflow/python/framework/registry.py", line 67, in register
    stack = traceback.extract_stack()
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/traceback.py", line 207, in extract_stack
    stack = StackSummary.extract(walk_stack(f), limit=limit)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/traceback.py", line 345, in extract
    linecache.lazycache(filename, f.f_globals)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/linecache.py", line 165, in lazycache
    if not filename or (filename.startswith('<') and filename.endswith('>')):
KeyboardInterrupt
Traceback (most recent call last):
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/codeMan/Desktop/mTRPO/mytrpo/trpo_mpi/run_mujoco.py", line 2, in <module>
    import tensorflow as tf
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site-packages/tensorflow/python/__init__.py", line 93, in <module>
    from tensorflow.python.ops.standard_ops import *
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site-packages/tensorflow/python/ops/standard_ops.py", line 28, in <module>
    from tensorflow.python.ops import math_grad
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site-packages/tensorflow/python/ops/math_grad.py", line 183, in <module>
    @ops.RegisterGradient("SparseSegmentSqrtN")
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1634, in __call__
    _gradient_registry.register(f, self._op_type)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site-packages/tensorflow/python/framework/registry.py", line 67, in register
    stack = traceback.extract_stack()
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/traceback.py", line 207, in extract_stack
    stack = StackSummary.extract(walk_stack(f), limit=limit)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/traceback.py", line 358, in extract
    f.line
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/traceback.py", line 282, in line
    self._line = linecache.getline(self.filename, self.lineno).strip()
KeyboardInterrupt
Traceback (most recent call last):
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/codeMan/Desktop/mTRPO/mytrpo/trpo_mpi/run_mujoco.py", line 2, in <module>
    import tensorflow as tf
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site-packages/tensorflow/python/__init__.py", line 93, in <module>
    from tensorflow.python.ops.standard_ops import *
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site-packages/tensorflow/python/ops/standard_ops.py", line 30, in <module>
    from tensorflow.python.ops import state_grad
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site-packages/tensorflow/python/ops/state_grad.py", line 48, in <module>
    ops.NotDifferentiable("ScatterNdUpdate")
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1668, in NotDifferentiable
    _gradient_registry.register(None, op_type)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site-packages/tensorflow/python/framework/registry.py", line 67, in register
    stack = traceback.extract_stack()
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/traceback.py", line 207, in extract_stack
    stack = StackSummary.extract(walk_stack(f), limit=limit)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/traceback.py", line 345, in extract
    linecache.lazycache(filename, f.f_globals)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/linecache.py", line 165, in lazycache
    if not filename or (filename.startswith('<') and filename.endswith('>')):
KeyboardInterrupt

real	0m1.882s
user	0m12.017s
sys	0m1.065s
timesteps 4000000
mpirun: killing job...

Traceback (most recent call last):
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/codeMan/Desktop/mTRPO/mytrpo/trpo_mpi/run_mujoco.py", line 2, in <module>
    import tensorflow as tf
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site-packages/tensorflow/python/__init__.py", line 29, in <module>
    import inspect
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/inspect.py", line 1025, in <module>
    ArgSpec = namedtuple('ArgSpec', 'args varargs keywords defaults')
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/collections/__init__.py", line 428, in namedtuple
    exec(class_definition, namespace)
  File "<string>", line 1, in <module>
KeyboardInterrupt
Traceback (most recent call last):
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/codeMan/Desktop/mTRPO/mytrpo/trpo_mpi/run_mujoco.py", line 2, in <module>
    import tensorflow as tf
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site-packages/tensorflow/python/__init__.py", line 29, in <module>
    import inspect
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/inspect.py", line 856, in <module>
    class BlockFinder:
KeyboardInterrupt
Traceback (most recent call last):
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/codeMan/Desktop/mTRPO/mytrpo/trpo_mpi/run_mujoco.py", line 2, in <module>
    import tensorflow as tf
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site-packages/tensorflow/python/__init__.py", line 29, in <module>
    import inspect
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/inspect.py", line 985, in <module>
    Arguments = namedtuple('Arguments', 'args, varargs, varkw')
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/collections/__init__.py", line 428, in namedtuple
    exec(class_definition, namespace)
  File "<string>", line 1, in <module>
KeyboardInterrupt
Traceback (most recent call last):
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/codeMan/Desktop/mTRPO/mytrpo/trpo_mpi/run_mujoco.py", line 2, in <module>
    import tensorflow as tf
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site-packages/tensorflow/python/__init__.py", line 29, in <module>
    import inspect
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/inspect.py", line 627, in <module>
    ModuleInfo = namedtuple('ModuleInfo', 'name suffix mode module_type')
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/collections/__init__.py", line 428, in namedtuple
    exec(class_definition, namespace)
  File "<string>", line 1, in <module>
KeyboardInterrupt
Traceback (most recent call last):
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/codeMan/Desktop/mTRPO/mytrpo/trpo_mpi/run_mujoco.py", line 2, in <module>
    import tensorflow as tf
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site-packages/tensorflow/python/__init__.py", line 29, in <module>
    import inspect
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/inspect.py", line 323, in <module>
    Attribute = namedtuple('Attribute', 'name kind defining_class object')
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/collections/__init__.py", line 428, in namedtuple
    exec(class_definition, namespace)
  File "<string>", line 1, in <module>
KeyboardInterrupt
Traceback (most recent call last):
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/codeMan/Desktop/mTRPO/mytrpo/trpo_mpi/run_mujoco.py", line 2, in <module>
    import tensorflow as tf
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site-packages/tensorflow/python/__init__.py", line 29, in <module>
    import inspect
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/inspect.py", line 40, in <module>
    import linecache
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/linecache.py", line 11, in <module>
    import tokenize
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/tokenize.py", line 215, in <module>
    single_quoted[t] = t
KeyboardInterrupt

real	0m0.172s
user	0m0.852s
sys	0m0.180s
mpirun: killing job...

Traceback (most recent call last):
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/codeMan/Desktop/mTRPO/mytrpo/trpo_mpi/run_mujoco.py", line 2, in <module>
    import tensorflow as tf
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site-packages/tensorflow/python/__init__.py", line 75, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site-packages/tensorflow/core/framework/graph_pb2.py", line 6, in <module>
    from google.protobuf import descriptor as _descriptor
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site-packages/google/protobuf/__init__.py", line 37, in <module>
    __import__('pkg_resources').declare_namespace(__name__)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site-packages/pkg_resources/__init__.py", line 33, in <module>
    import platform
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/platform.py", line 117, in <module>
    import sys, os, re, subprocess
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 661, in exec_module
  File "<frozen importlib._bootstrap_external>", line 765, in get_code
  File "<frozen importlib._bootstrap_external>", line 476, in _compile_bytecode
KeyboardInterrupt
Traceback (most recent call last):
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/codeMan/Desktop/mTRPO/mytrpo/trpo_mpi/run_mujoco.py", line 2, in <module>
    import tensorflow as tf
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site-packages/tensorflow/python/__init__.py", line 75, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site-packages/tensorflow/core/framework/graph_pb2.py", line 6, in <module>
    from google.protobuf import descriptor as _descriptor
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site-packages/google/protobuf/__init__.py", line 37, in <module>
    __import__('pkg_resources').declare_namespace(__name__)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site-packages/pkg_resources/__init__.py", line 33, in <module>
    import platform
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 954, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 896, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1139, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1113, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1249, in find_spec
  File "<frozen importlib._bootstrap_external>", line 366, in _verbose_message
KeyboardInterrupt
Traceback (most recent call last):
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/codeMan/Desktop/mTRPO/mytrpo/trpo_mpi/run_mujoco.py", line 2, in <module>
    import tensorflow as tf
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site-packages/tensorflow/python/__init__.py", line 75, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site-packages/tensorflow/core/framework/graph_pb2.py", line 6, in <module>
    from google.protobuf import descriptor as _descriptor
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site-packages/google/protobuf/__init__.py", line 37, in <module>
    __import__('pkg_resources').declare_namespace(__name__)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site-packages/pkg_resources/__init__.py", line 33, in <module>
    import platform
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/platform.py", line 1154, in <module>
    r'\[([^\]]+)\]?', re.ASCII)  # "[compiler]"
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/re.py", line 224, in compile
    return _compile(pattern, flags)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/re.py", line 293, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/sre_compile.py", line 536, in compile
    p = sre_parse.parse(p, flags)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/sre_parse.py", line 829, in parse
    p = _parse_sub(source, pattern, 0)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/sre_parse.py", line 437, in _parse_sub
    itemsappend(_parse(source, state))
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/sre_parse.py", line 493, in _parse
    subpattern = SubPattern(state)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/sre_parse.py", line 110, in __init__
    self.width = None
KeyboardInterrupt
Traceback (most recent call last):
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/codeMan/Desktop/mTRPO/mytrpo/trpo_mpi/run_mujoco.py", line 2, in <module>
    import tensorflow as tf
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site-packages/tensorflow/python/__init__.py", line 75, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site-packages/tensorflow/core/framework/graph_pb2.py", line 6, in <module>
    from google.protobuf import descriptor as _descriptor
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site-packages/google/protobuf/__init__.py", line 37, in <module>
    __import__('pkg_resources').declare_namespace(__name__)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site-packages/pkg_resources/__init__.py", line 33, in <module>
    import platform
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/platform.py", line 410, in <module>
    _ver_output = re.compile(r'(?:([\w ]+) ([\w.]+) '
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/re.py", line 224, in compile
    return _compile(pattern, flags)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/re.py", line 293, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/sre_compile.py", line 536, in compile
    p = sre_parse.parse(p, flags)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/sre_parse.py", line 829, in parse
    p = _parse_sub(source, pattern, 0)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/sre_parse.py", line 437, in _parse_sub
    itemsappend(_parse(source, state))
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/sre_parse.py", line 778, in _parse
    p = _parse_sub(source, state)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/sre_parse.py", line 437, in _parse_sub
    itemsappend(_parse(source, state))
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/sre_parse.py", line 778, in _parse
    p = _parse_sub(source, state)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/sre_parse.py", line 437, in _parse_sub
    itemsappend(_parse(source, state))
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/sre_parse.py", line 549, in _parse
    code1 = _class_escape(source, this)
KeyboardInterrupt

real	0m0.519s
user	0m2.848s
sys	0m0.619s
mpirun: killing job...

Fatal Python error: Py_Initialize: can't initialize sys standard streams
Traceback (most recent call last):
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/io.py", line 52, in <module>
Fatal Python error: Py_Initialize: can't initialize sys standard streams
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
Fatal Python error: Py_Initialize: can't initialize sys standard streams
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load

real	0m0.065s
user	0m0.148s
sys	0m0.053s
mpirun: killing job...

Failed to import the site module
Failed to import the site module
Failed to import the site module
Failed to import the site module
Failed to import the site module
Failed to import the site module
Failed to import the site module
Failed to import the site module
Traceback (most recent call last):
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 567, in <module>
    main()
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 545, in main
    known_paths = removeduppaths()
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 125, in removeduppaths
    dir, dircase = makepath(dir)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 92, in makepath
    dir = os.path.abspath(dir)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/posixpath.py", line 361, in abspath
    cwd = os.getcwd()
KeyboardInterrupt
Traceback (most recent call last):
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 567, in <module>
    main()
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 545, in main
    known_paths = removeduppaths()
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 125, in removeduppaths
    dir, dircase = makepath(dir)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 92, in makepath
    dir = os.path.abspath(dir)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/posixpath.py", line 355, in abspath
    def abspath(path):
KeyboardInterrupt
Traceback (most recent call last):
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 72, in <module>
    import os
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/os.py", line 708, in <module>
    from _collections_abc import MutableMapping
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/_collections_abc.py", line 682, in <module>
    class ValuesView(MappingView):
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/abc.py", line 133, in __new__
    cls = super().__new__(mcls, name, bases, namespace)
KeyboardInterrupt
Traceback (most recent call last):
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 72, in <module>
    import os
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/os.py", line 708, in <module>
    from _collections_abc import MutableMapping
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/_collections_abc.py", line 699, in <module>
    class MutableMapping(Mapping):
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/abc.py", line 133, in __new__
    cls = super().__new__(mcls, name, bases, namespace)
KeyboardInterrupt
Traceback (most recent call last):
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 72, in <module>
    import os
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/os.py", line 57, in <module>
    import posixpath as path
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/posixpath.py", line 16, in <module>
    import genericpath
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 661, in exec_module
  File "<frozen importlib._bootstrap_external>", line 750, in get_code
  File "<frozen importlib._bootstrap_external>", line 818, in get_data
KeyboardInterrupt
Traceback (most recent call last):
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/os.py", line 42, in _get_exports_list
    return list(module.__all__)
AttributeError: module 'posix' has no attribute '__all__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 72, in <module>
    import os
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/os.py", line 65, in <module>
    __all__.extend(_get_exports_list(posix))
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/os.py", line 44, in _get_exports_list
    return [n for n in dir(module) if n[0] != '_']
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/os.py", line 44, in <listcomp>
    return [n for n in dir(module) if n[0] != '_']
KeyboardInterrupt

real	0m0.082s
user	0m0.280s
sys	0m0.078s
mpirun: killing job...

Failed to import the site module
Failed to import the site module
Failed to import the site module
Failed to import the site module
Failed to import the site module
Failed to import the site module
Traceback (most recent call last):
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 72, in <module>
    import os
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/os.py", line 708, in <module>
    from _collections_abc import MutableMapping
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/_collections_abc.py", line 797, in <module>
    class Sequence(Sized, Iterable, Container):
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/abc.py", line 141, in __new__
    if getattr(value, "__isabstractmethod__", False):
KeyboardInterrupt
Traceback (most recent call last):
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 72, in <module>
    import os
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/os.py", line 708, in <module>
    from _collections_abc import MutableMapping
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 171, in __exit__
  File "<frozen importlib._bootstrap>", line 122, in release
KeyboardInterrupt
Traceback (most recent call last):
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 72, in <module>
    import os
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/os.py", line 708, in <module>
    from _collections_abc import MutableMapping
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/_collections_abc.py", line 682, in <module>
    class ValuesView(MappingView):
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/abc.py", line 133, in __new__
    cls = super().__new__(mcls, name, bases, namespace)
KeyboardInterrupt
Failed to import the site module
Traceback (most recent call last):
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 72, in <module>
    import os
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/os.py", line 708, in <module>
    from _collections_abc import MutableMapping
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 661, in exec_module
  File "<frozen importlib._bootstrap_external>", line 765, in get_code
  File "<frozen importlib._bootstrap_external>", line 476, in _compile_bytecode
KeyboardInterrupt
Traceback (most recent call last):
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 72, in <module>
    import os
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/os.py", line 708, in <module>
    from _collections_abc import MutableMapping
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/_collections_abc.py", line 297, in <module>
    Generator.register(generator)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/abc.py", line 158, in register
    if issubclass(subclass, cls):
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/abc.py", line 207, in __subclasscheck__
    ok = cls.__subclasshook__(subclass)
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/_collections_abc.py", line 289, in __subclasshook__
    if method in base.__dict__:
KeyboardInterrupt
Traceback (most recent call last):
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/site.py", line 72, in <module>
    import os
  File "/Users/codeMan/anaconda3/envs/keras/lib/python3.5/os.py", line 57, in <module>
    import posixpath as path
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 954, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 896, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1139, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1113, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1251, in find_spec
  File "<frozen importlib._bootstrap_external>", line 89, in _path_isfile
  File "<frozen importlib._bootstrap_external>", line 81, in _path_is_mode_type
  File "<frozen importlib._bootstrap_external>", line 75, in _path_stat
KeyboardInterrupt

real	0m0.083s
user	0m0.277s
sys	0m0.080s
